
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MyMLProject.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MyMLProject.ModelInput sampleData = new MyMLProject.ModelInput()
            {
                No_of_dependents = 2F,
                Education = @"Graduate",
                Income_annum = 9600000F,
                Loan_amount = 29900000F,
                Loan_term = 12F,
                Cibil_score = 778F,
                Residential_assets_value = 2400000F,
                Commercial_assets_value = 17600000F,
                Luxury_assets_value = 22700000F,
                Bank_asset_value = 8000000F,
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual Loan_status with predicted Loan_status from sample data...\n\n");


            Console.WriteLine($"No_of_dependents: {2F}");
            Console.WriteLine($"Education: {@"Graduate"}");
            Console.WriteLine($"Income_annum: {9600000F}");
            Console.WriteLine($"Loan_amount: {29900000F}");
            Console.WriteLine($"Loan_term: {12F}");
            Console.WriteLine($"Cibil_score: {778F}");
            Console.WriteLine($"Residential_assets_value: {2400000F}");
            Console.WriteLine($"Commercial_assets_value: {17600000F}");
            Console.WriteLine($"Luxury_assets_value: {22700000F}");
            Console.WriteLine($"Bank_asset_value: {8000000F}");
            Console.WriteLine($"Loan_status: {1F}");


            var sortedScoresWithLabel = MyMLProject.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
